fileName = input('Enter file name: ');
fid = fopen(fileName,'r');
fSize = input('Enter file size: ');
Input = fread(fid,[fSize,fSize],'uchar');
fclose(fid);
Qf= input('Enter Quantization step size: ');
Q=zeros(1,5);
Q(4)=Qf;
Q(3)=Qf*2;
Q(2)=Qf*3;
Q(1)=Qf*4;
pic1=HaarTrans(Input);
pic2=quant(pic1,Q,fSize);
bitStream(pic2,Q,fSize);
fid=fopen('bit.bin','r');
Input2=fread(fid,[256,256],'uchar');
fclose(fid);
Input2=quantinv(pic2,Q,fSize);
Output=HaarTransInv(Input2);
psnr(Input,Output);
dispImg(Output);